# Generated by Django 4.1 on 2024-02-07 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('guid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Make', models.CharField(blank=True, max_length=255)),
                ('Model', models.CharField(blank=True, max_length=255)),
                ('Category', models.CharField(blank=True, max_length=255)),
                ('Class', models.CharField(blank=True, max_length=255)),
                ('EngType', models.CharField(default='N/A', max_length=255, verbose_name='EngineType')),
                ('Complex', models.BooleanField()),
                ('HighPerf', models.BooleanField(verbose_name='HighPerformance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Airfield',
            fields=[
                ('guid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('AFName', models.CharField(max_length=255, verbose_name='Approach1')),
                ('City', models.CharField(blank=True, max_length=255, verbose_name='Approach2')),
                ('Notes', models.CharField(blank=True, max_length=255, verbose_name='Approach3')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('guid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('PilotName', models.CharField(blank=True, max_length=255, verbose_name='Person1')),
                ('PilotEMail', models.CharField(blank=True, max_length=255, verbose_name='Person2')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('guid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('DateLOCAL', models.CharField(max_length=255, verbose_name='Date')),
                ('Route', models.CharField(blank=True, max_length=255)),
                ('DepTimeUTC', models.CharField(max_length=255, verbose_name='TimeOut')),
                ('ArrTimeUTC', models.CharField(max_length=255, verbose_name='TimeIn')),
                ('minTOTAL', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='TotalTime')),
                ('airfield_data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_handler.airfield')),
                ('pilot_data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_handler.pilot')),
            ],
            options={
                'verbose_name_plural': 'Flights',
            },
        ),
    ]
